/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelGrIndexRouteImport } from './routes/painel-gr.index'
import { Route as PainelGrLoginRouteImport } from './routes/painel-gr.login'
import { Route as PainelGrGatewaysRouteImport } from './routes/painel-gr.gateways'
import { Route as ApiPublicMonetrixWebhookRouteImport } from './routes/api/public/monetrix-webhook'
import { Route as ApiPublicClarexUploadRouteImport } from './routes/api/public/clarex-upload'
import { Route as ApiPublicHooksZapiDeliveryRouteImport } from './routes/api/public/hooks/zapi-delivery'
import { Route as ApiPublicHooksOrderNotificationsRouteImport } from './routes/api/public/hooks/order-notifications'
import { Route as ApiPublicHooksExpirePixRouteImport } from './routes/api/public/hooks/expire-pix'
import { Route as ApiPublicHooksCartRecoveryRouteImport } from './routes/api/public/hooks/cart-recovery'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelGrIndexRoute = PainelGrIndexRouteImport.update({
  id: '/painel-gr/',
  path: '/painel-gr/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelGrLoginRoute = PainelGrLoginRouteImport.update({
  id: '/painel-gr/login',
  path: '/painel-gr/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelGrGatewaysRoute = PainelGrGatewaysRouteImport.update({
  id: '/painel-gr/gateways',
  path: '/painel-gr/gateways',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMonetrixWebhookRoute =
  ApiPublicMonetrixWebhookRouteImport.update({
    id: '/api/public/monetrix-webhook',
    path: '/api/public/monetrix-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClarexUploadRoute = ApiPublicClarexUploadRouteImport.update({
  id: '/api/public/clarex-upload',
  path: '/api/public/clarex-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksZapiDeliveryRoute =
  ApiPublicHooksZapiDeliveryRouteImport.update({
    id: '/api/public/hooks/zapi-delivery',
    path: '/api/public/hooks/zapi-delivery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOrderNotificationsRoute =
  ApiPublicHooksOrderNotificationsRouteImport.update({
    id: '/api/public/hooks/order-notifications',
    path: '/api/public/hooks/order-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpirePixRoute = ApiPublicHooksExpirePixRouteImport.update({
  id: '/api/public/hooks/expire-pix',
  path: '/api/public/hooks/expire-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCartRecoveryRoute =
  ApiPublicHooksCartRecoveryRouteImport.update({
    id: '/api/public/hooks/cart-recovery',
    path: '/api/public/hooks/cart-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/painel-gr/gateways': typeof PainelGrGatewaysRoute
  '/painel-gr/login': typeof PainelGrLoginRoute
  '/painel-gr/': typeof PainelGrIndexRoute
  '/api/public/clarex-upload': typeof ApiPublicClarexUploadRoute
  '/api/public/monetrix-webhook': typeof ApiPublicMonetrixWebhookRoute
  '/api/public/hooks/cart-recovery': typeof ApiPublicHooksCartRecoveryRoute
  '/api/public/hooks/expire-pix': typeof ApiPublicHooksExpirePixRoute
  '/api/public/hooks/order-notifications': typeof ApiPublicHooksOrderNotificationsRoute
  '/api/public/hooks/zapi-delivery': typeof ApiPublicHooksZapiDeliveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/painel-gr/gateways': typeof PainelGrGatewaysRoute
  '/painel-gr/login': typeof PainelGrLoginRoute
  '/painel-gr': typeof PainelGrIndexRoute
  '/api/public/clarex-upload': typeof ApiPublicClarexUploadRoute
  '/api/public/monetrix-webhook': typeof ApiPublicMonetrixWebhookRoute
  '/api/public/hooks/cart-recovery': typeof ApiPublicHooksCartRecoveryRoute
  '/api/public/hooks/expire-pix': typeof ApiPublicHooksExpirePixRoute
  '/api/public/hooks/order-notifications': typeof ApiPublicHooksOrderNotificationsRoute
  '/api/public/hooks/zapi-delivery': typeof ApiPublicHooksZapiDeliveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/painel-gr/gateways': typeof PainelGrGatewaysRoute
  '/painel-gr/login': typeof PainelGrLoginRoute
  '/painel-gr/': typeof PainelGrIndexRoute
  '/api/public/clarex-upload': typeof ApiPublicClarexUploadRoute
  '/api/public/monetrix-webhook': typeof ApiPublicMonetrixWebhookRoute
  '/api/public/hooks/cart-recovery': typeof ApiPublicHooksCartRecoveryRoute
  '/api/public/hooks/expire-pix': typeof ApiPublicHooksExpirePixRoute
  '/api/public/hooks/order-notifications': typeof ApiPublicHooksOrderNotificationsRoute
  '/api/public/hooks/zapi-delivery': typeof ApiPublicHooksZapiDeliveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/painel-gr/gateways'
    | '/painel-gr/login'
    | '/painel-gr/'
    | '/api/public/clarex-upload'
    | '/api/public/monetrix-webhook'
    | '/api/public/hooks/cart-recovery'
    | '/api/public/hooks/expire-pix'
    | '/api/public/hooks/order-notifications'
    | '/api/public/hooks/zapi-delivery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/painel-gr/gateways'
    | '/painel-gr/login'
    | '/painel-gr'
    | '/api/public/clarex-upload'
    | '/api/public/monetrix-webhook'
    | '/api/public/hooks/cart-recovery'
    | '/api/public/hooks/expire-pix'
    | '/api/public/hooks/order-notifications'
    | '/api/public/hooks/zapi-delivery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/painel-gr/gateways'
    | '/painel-gr/login'
    | '/painel-gr/'
    | '/api/public/clarex-upload'
    | '/api/public/monetrix-webhook'
    | '/api/public/hooks/cart-recovery'
    | '/api/public/hooks/expire-pix'
    | '/api/public/hooks/order-notifications'
    | '/api/public/hooks/zapi-delivery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PainelGrGatewaysRoute: typeof PainelGrGatewaysRoute
  PainelGrLoginRoute: typeof PainelGrLoginRoute
  PainelGrIndexRoute: typeof PainelGrIndexRoute
  ApiPublicClarexUploadRoute: typeof ApiPublicClarexUploadRoute
  ApiPublicMonetrixWebhookRoute: typeof ApiPublicMonetrixWebhookRoute
  ApiPublicHooksCartRecoveryRoute: typeof ApiPublicHooksCartRecoveryRoute
  ApiPublicHooksExpirePixRoute: typeof ApiPublicHooksExpirePixRoute
  ApiPublicHooksOrderNotificationsRoute: typeof ApiPublicHooksOrderNotificationsRoute
  ApiPublicHooksZapiDeliveryRoute: typeof ApiPublicHooksZapiDeliveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-gr/': {
      id: '/painel-gr/'
      path: '/painel-gr'
      fullPath: '/painel-gr/'
      preLoaderRoute: typeof PainelGrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-gr/login': {
      id: '/painel-gr/login'
      path: '/painel-gr/login'
      fullPath: '/painel-gr/login'
      preLoaderRoute: typeof PainelGrLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-gr/gateways': {
      id: '/painel-gr/gateways'
      path: '/painel-gr/gateways'
      fullPath: '/painel-gr/gateways'
      preLoaderRoute: typeof PainelGrGatewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monetrix-webhook': {
      id: '/api/public/monetrix-webhook'
      path: '/api/public/monetrix-webhook'
      fullPath: '/api/public/monetrix-webhook'
      preLoaderRoute: typeof ApiPublicMonetrixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarex-upload': {
      id: '/api/public/clarex-upload'
      path: '/api/public/clarex-upload'
      fullPath: '/api/public/clarex-upload'
      preLoaderRoute: typeof ApiPublicClarexUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/zapi-delivery': {
      id: '/api/public/hooks/zapi-delivery'
      path: '/api/public/hooks/zapi-delivery'
      fullPath: '/api/public/hooks/zapi-delivery'
      preLoaderRoute: typeof ApiPublicHooksZapiDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/order-notifications': {
      id: '/api/public/hooks/order-notifications'
      path: '/api/public/hooks/order-notifications'
      fullPath: '/api/public/hooks/order-notifications'
      preLoaderRoute: typeof ApiPublicHooksOrderNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-pix': {
      id: '/api/public/hooks/expire-pix'
      path: '/api/public/hooks/expire-pix'
      fullPath: '/api/public/hooks/expire-pix'
      preLoaderRoute: typeof ApiPublicHooksExpirePixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cart-recovery': {
      id: '/api/public/hooks/cart-recovery'
      path: '/api/public/hooks/cart-recovery'
      fullPath: '/api/public/hooks/cart-recovery'
      preLoaderRoute: typeof ApiPublicHooksCartRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PainelGrGatewaysRoute: PainelGrGatewaysRoute,
  PainelGrLoginRoute: PainelGrLoginRoute,
  PainelGrIndexRoute: PainelGrIndexRoute,
  ApiPublicClarexUploadRoute: ApiPublicClarexUploadRoute,
  ApiPublicMonetrixWebhookRoute: ApiPublicMonetrixWebhookRoute,
  ApiPublicHooksCartRecoveryRoute: ApiPublicHooksCartRecoveryRoute,
  ApiPublicHooksExpirePixRoute: ApiPublicHooksExpirePixRoute,
  ApiPublicHooksOrderNotificationsRoute: ApiPublicHooksOrderNotificationsRoute,
  ApiPublicHooksZapiDeliveryRoute: ApiPublicHooksZapiDeliveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
